# ref: http://docs.travis-ci.com/user/build-configuration

language: erlang

sudo: false

env:
    global:
        - DEPS_BUILD_DIR=$TRAVIS_BUILD_DIR/deps
        - DEPS_PREFIX=$DEPS_BUILD_DIR/dist
        - DEPS_BIN_DIR=$DEPS_PREFIX/dist/bin
        - LJ_REPO="http://luajit.org/git/luajit-2.0.git"
    matrix:
        - LUA=lua-5.2    LUA_TYPE=lua    LUA_BIN=lua     LUA_DIST=lua-5.2.4
        - LUA=lua-5.3    LUA_TYPE=lua    LUA_BIN=lua     LUA_DIST=lua-5.3.1
        - LUA=luajit-2.0 LUA_TYPE=luajit LUA_BIN=luajit             LJ_BR=master
        - LUA=luajit-2.1 LUA_TYPE=luajit LUA_BIN=luajit-2.1.0-beta1 LJ_BR=v2.1

before_install:
    - mkdir -p $DEPS_BUILD_DIR
    #- sudo apt-get update -q

install:
    # install LuaJIT
    - cd $DEPS_BUILD_DIR
    - if [ "$LUA_TYPE" == "luajit" ]; then
          git clone -b $LJ_BR $LJ_REPO luajit2.git && cd luajit2.git && make PREFIX=$DEPS_PREFIX XCFLAGS+="-DLUAJIT_ENABLE_LUA52COMPAT" install;
      fi
    - if [ "$LUA_TYPE" == "lua" ]; then
          wget "http://www.lua.org/ftp/$LUA_DIST.tar.gz" && tar xzf $LUA_DIST.tar.gz && cd $LUA_DIST && make linux test install INSTALL_TOP=$DEPS_PREFIX;
      fi

before_script:
    # back to home directory
    - cd $TRAVIS_BUILD_DIR
    # update the path
    - export PATH=$PATH:$DEPS_BIN_DIR
    - echo $PATH
    # check executables
    - which $LUA_BIN 2>/dev/null && $LUA_BIN -v

script:
    - $LUA_BIN rc4.lua

notifications:
    email:
        on_success: change
        on_failure: always
